services: 
    mixtend:
        container_name: mixtend
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db_mixtend
  

    db_mixtend:
        container_name: db_mixtend
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: ets
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306